### ISSUE TITLE
Integration in Scipion?

### ISSUE THREAD

**Issue by pconesa** [thuem/THUNDER#17]
Dear THUNDER developers, we have received a request to integrate THUNDER in Scipion.
We haven't got the manpower to integrate it, but we can guide/help /assist any developer that might want to integrate it.

We think good reasons can be found here: http://scipion.i2pc.es/developers

If you are interested in reaching a wider audience, let us know, and we can find a way to collaborate.

**Comment by snowlxm** [comment]
We would like to be integrated in Scipion. But we also don't have extra people to work on it now, we can provide any help or answer questions if you need.

**Comment by pconesa** [comment]
@snowlxm thank you for the reply....I'll have to wait then until we or you find some time. 

All the best, Pablo
