### ISSUE TITLE
E-mail notification test

### ISSUE THREAD

**Issue by thuem** [thuem/THUNDER#9]
only for E-mail notification test

**Comment by thuem** [comment]
test for receiving e-mail

**Comment by Zarrathustra** [comment]
test for receiving e-mail

**Comment by Zarrathustra** [comment]
test for receiving e-mail

**Comment by Zarrathustra** [comment]
test for receiving e-mail

**Comment by Zarrathustra** [comment]
test for receiving e-mail

**Comment by Zarrathustra** [comment]
check whether Prof. Li receive the notification E-mail or not

**Comment by Zarrathustra** [comment]
check whether Prof. Li receive the notification E-mail or not

**Comment by thuem** [comment]
check whether Dr. Hu receive the notification E-mail or not

**Comment by Zarrathustra** [comment]
check whether Dr. Hu receive the notification E-mail or not

**Comment by Zarrathustra** [comment]
check whether aliyun.com receive the notification E-mail or not

**Comment by Zarrathustra** [comment]
check whether aliyun.com receive the notification E-mail and forward it to Dr. Hu or not

**Comment by Zarrathustra** [comment]
check whether aliyun.com receive the notification E-mail and forward it to Prof. Li, Dr. Ruan and Dr. Hu, or not

**Comment by Zarrathustra** [comment]
check whether aliyun.com receive the notification E-mail and forward it to Prof. Li, Dr. Ruan and Dr. Hu, or not, 2nd time trial

**Comment by Zarrathustra** [comment]
2nd time trial of auto-forwarding

**Comment by Zarrathustra** [comment]
3rd time trial of auto-forwarding

**Comment by Zarrathustra** [comment]
4th time trial of auto-forwarding

**Comment by Zarrathustra** [comment]
5th time trial of auto-forwarding
